language: node_js
node_js:
  - "stable"
  - "4"
  - "6"
branches:
  only:
    - master
script:
  - "npm run-script cover"
  - "npm run-script lint"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
